version: '3'
services:
  session-handler:
    build:
      context: ./
      dockerfile: Dockerfile
    image: session-handler-v1.01
    ports:
      - 9000:9000

networks:
  default:
    external:
      name: offtop-network